pipeline {
    agent any
    environment {
        BRANCH_NAME = "${env.GIT_BRANCH.split("/")[1]}"
        branch = "*/${BRANCH_NAME}"
    }
    stages {
        stage ("build") {
            steps {
                echo "backend build again"
               //echo env.GIT_BRANCH.split("/")[1]
            }
        }
        stage ('Git checkout') {
             steps {
               sh 'echo "$BRANCH_NAME"'
               sh 'echo "$branch"'
               checkout([$class: 'GitSCM', branches: [[name: "$branch"]], extensions: [], userRemoteConfigs: [[credentialsId: 'git_credentials', url: 'https://lk436370@dev.azure.com/lk436370/testdemo/_git/testdemo']]])
            }
        }    
    }
}